<?php
declare(strict_types=1);
namespace App\Services;
use App\Libraries\AuditLogger;
use App\Models\SalesDocumentItemModel;
use App\Models\SalesDocumentModel;
use App\Models\SalesDocumentStatusHistoryModel;
use App\Models\StockBalanceModel;
use App\Models\StockMovementModel;
use App\Models\StockReservationModel;
use RuntimeException;
use Throwable;
class StockService
{
    public function __construct(private readonly ?int $actorUserId=null){}
    public function move(int $warehouseId,int $variantId,float $quantity,string $type,string $reason,?string $referenceType=null,?int $referenceId=null):int
    {$db=db_connect();$db->transBegin();try{$id=$this->post($warehouseId,$variantId,$quantity,$type,$reason,$referenceType,$referenceId);if(!$db->transStatus())throw new RuntimeException('Stok hareketi kaydedilemedi.');$db->transCommit();return$id;}catch(Throwable $e){$db->transRollback();throw$e;}}
    public function transfer(int $from,int $to,int $variantId,float $quantity,string $reason):array
    {if($from===$to)throw new RuntimeException('Transfer depoları farklı olmalıdır.');if($quantity<=0)throw new RuntimeException('Transfer miktarı sıfırdan büyük olmalıdır.');$db=db_connect();$db->transBegin();try{$out=$this->post($from,$variantId,-$quantity,'transfer_out',$reason,'warehouse_transfer',null);$in=$this->post($to,$variantId,$quantity,'transfer_in',$reason,'warehouse_transfer',$out);$db->table('stock_movements')->where('id',$out)->update(['paired_movement_id'=>$in,'reference_id'=>$in]);$db->table('stock_movements')->where('id',$in)->update(['paired_movement_id'=>$out]);if(!$db->transStatus())throw new RuntimeException('Transfer kaydedilemedi.');$db->transCommit();return[$out,$in];}catch(Throwable $e){$db->transRollback();throw$e;}}
    public function reserveOrder(int $documentId,int $warehouseId):array
    {$document=(new SalesDocumentModel())->find($documentId);if(!$document||$document['document_type']!=='order'||!in_array($document['status'],['approved','procurement_waiting','partially_shipped'],true))throw new RuntimeException('Yalnızca onaylı veya tedarik bekleyen siparişe ürün ayrılabilir.');$items=(new SalesDocumentItemModel())->where('sales_document_id',$documentId)->findAll();$db=db_connect();$db->transBegin();$reserved=0.0;$missing=0.0;try{foreach($items as $item){$needed=(float)$item['quantity']-(float)$item['reserved_quantity']-(float)$item['fulfilled_quantity'];if($needed<=0)continue;$balance=$this->balance($warehouseId,(int)$item['product_variant_id']);$available=max(0,(float)$balance['on_hand_quantity']-(float)$balance['reserved_quantity']);$qty=min($needed,$available);if($qty>0){(new StockBalanceModel())->update($balance['id'],['reserved_quantity'=>(float)$balance['reserved_quantity']+$qty]);(new StockReservationModel())->insert(['sales_document_item_id'=>$item['id'],'warehouse_id'=>$warehouseId,'reserved_quantity'=>$qty,'fulfilled_quantity'=>0,'status'=>'active','created_by_user_id'=>$this->userId()]);(new SalesDocumentItemModel())->update($item['id'],['reserved_quantity'=>(float)$item['reserved_quantity']+$qty]);$reserved+=$qty;}$missing+=$needed-$qty;}$status=$missing>0?'procurement_waiting':'reserved';(new SalesDocumentModel())->update($documentId,['status'=>$status]);$this->history($documentId,$document['status'],$status,$missing>0?'Mevcut stok ayrıldı; eksik ürün tedarik bekliyor.':'Sipariş için stok ayrıldı.');if(!$db->transStatus())throw new RuntimeException('Sipariş stoğu ayrılamadı.');$db->transCommit();}catch(Throwable $e){$db->transRollback();throw$e;}(new AuditLogger())->record('order.stock_reserved','sales_document',$documentId,['status'=>$document['status']],['status'=>$status,'reserved'=>$reserved,'missing'=>$missing]);return['reserved'=>$reserved,'missing'=>$missing,'status'=>$status];}
    public function shipReserved(int $documentId,string $reason):array
    {if(trim($reason)==='')throw new RuntimeException('Sevkiyat açıklaması zorunludur.');$document=(new SalesDocumentModel())->find($documentId);if(!$document||!in_array($document['status'],['reserved','procurement_waiting','partially_shipped'],true))throw new RuntimeException('Bu siparişte sevk edilebilir ayrılmış stok yok.');$db=db_connect();$rows=$db->table('stock_reservations sr')->select('sr.*,sdi.product_variant_id')->join('sales_document_items sdi','sdi.id=sr.sales_document_item_id')->where('sdi.sales_document_id',$documentId)->where('sr.status','active')->get()->getResultArray();if($rows===[])throw new RuntimeException('Sevk edilecek aktif stok ayırması bulunamadı.');$db->transBegin();$shipped=0.0;try{foreach($rows as $row){$qty=(float)$row['reserved_quantity']-(float)$row['fulfilled_quantity'];if($qty<=0)continue;$balance=$this->balance((int)$row['warehouse_id'],(int)$row['product_variant_id']);if((float)$balance['on_hand_quantity']<$qty||(float)$balance['reserved_quantity']<$qty)throw new RuntimeException('Ayrılmış stok bakiyesi tutarsız; sevkiyat durduruldu.');$after=(float)$balance['on_hand_quantity']-$qty;(new StockBalanceModel())->update($balance['id'],['on_hand_quantity'=>$after,'reserved_quantity'=>(float)$balance['reserved_quantity']-$qty]);$this->insertMovement((int)$row['warehouse_id'],(int)$row['product_variant_id'],-$qty,$after,'shipment',$reason,'sales_document',$documentId);(new StockReservationModel())->update($row['id'],['fulfilled_quantity'=>(float)$row['reserved_quantity'],'status'=>'fulfilled']);$item=(new SalesDocumentItemModel())->find($row['sales_document_item_id']);(new SalesDocumentItemModel())->update($row['sales_document_item_id'],['reserved_quantity'=>max(0,(float)$item['reserved_quantity']-$qty),'fulfilled_quantity'=>(float)$item['fulfilled_quantity']+$qty]);$shipped+=$qty;}$remaining=(new SalesDocumentItemModel())->select('SUM(quantity-fulfilled_quantity) AS remaining',false)->where('sales_document_id',$documentId)->first();$status=(float)($remaining['remaining']??0)>0?'partially_shipped':'shipped';(new SalesDocumentModel())->update($documentId,['status'=>$status]);$this->history($documentId,$document['status'],$status,$reason);if(!$db->transStatus())throw new RuntimeException('Sevkiyat kaydedilemedi.');$db->transCommit();}catch(Throwable $e){$db->transRollback();throw$e;}(new AuditLogger())->record('order.shipped','sales_document',$documentId,['status'=>$document['status']],['status'=>$status,'quantity'=>$shipped,'reason'=>$reason]);return['shipped'=>$shipped,'status'=>$status];}
    public function releaseDocumentReservations(int $documentId):float
    {$db=db_connect();$rows=$db->table('stock_reservations sr')->select('sr.*,sdi.product_variant_id')->join('sales_document_items sdi','sdi.id=sr.sales_document_item_id')->where('sdi.sales_document_id',$documentId)->where('sr.status','active')->get()->getResultArray();$released=0.0;foreach($rows as $row){$qty=(float)$row['reserved_quantity']-(float)$row['fulfilled_quantity'];if($qty<=0)continue;$balance=$this->balance((int)$row['warehouse_id'],(int)$row['product_variant_id']);(new StockBalanceModel())->update($balance['id'],['reserved_quantity'=>max(0,(float)$balance['reserved_quantity']-$qty)]);(new StockReservationModel())->update($row['id'],['status'=>'released']);$item=(new SalesDocumentItemModel())->find($row['sales_document_item_id']);(new SalesDocumentItemModel())->update($row['sales_document_item_id'],['reserved_quantity'=>max(0,(float)$item['reserved_quantity']-$qty)]);$released+=$qty;}return$released;}
    public function balance(int $warehouseId,int $variantId):array
    {$model=new StockBalanceModel();$row=$model->where(['warehouse_id'=>$warehouseId,'product_variant_id'=>$variantId])->first();if($row)return$row;if(!$model->insert(['warehouse_id'=>$warehouseId,'product_variant_id'=>$variantId,'on_hand_quantity'=>0,'reserved_quantity'=>0]))throw new RuntimeException('Stok bakiyesi oluşturulamadı.');return$model->find($model->getInsertID());}
    private function post(int $warehouseId,int $variantId,float $quantity,string $type,string $reason,?string $referenceType,?int $referenceId):int
    {if(abs($quantity)<0.0005)throw new RuntimeException('Stok hareket miktarı sıfır olamaz.');if(trim($reason)==='')throw new RuntimeException('Stok hareketi nedeni zorunludur.');$balance=$this->balance($warehouseId,$variantId);$available=(float)$balance['on_hand_quantity']-(float)$balance['reserved_quantity'];if($quantity<0&&abs($quantity)>$available+0.0001)throw new RuntimeException('Kullanılabilir stok yetersiz; stok eksiye düşürülemez.');$after=(float)$balance['on_hand_quantity']+$quantity;(new StockBalanceModel())->update($balance['id'],['on_hand_quantity'=>$after]);return$this->insertMovement($warehouseId,$variantId,$quantity,$after,$type,$reason,$referenceType,$referenceId);}
    private function insertMovement(int $warehouseId,int $variantId,float $quantity,float $after,string $type,string $reason,?string $referenceType,?int $referenceId):int{$model=new StockMovementModel();$model->insert(['movement_number'=>$this->number(),'movement_type'=>$type,'warehouse_id'=>$warehouseId,'product_variant_id'=>$variantId,'quantity'=>$quantity,'balance_after'=>$after,'reason'=>trim($reason),'reference_type'=>$referenceType,'reference_id'=>$referenceId,'created_by_user_id'=>$this->userId(),'created_at'=>date('Y-m-d H:i:s')]);return(int)$model->getInsertID();}
    private function history(int $id,?string $old,string $new,string $reason):void{(new SalesDocumentStatusHistoryModel())->insert(['sales_document_id'=>$id,'old_status'=>$old,'new_status'=>$new,'reason'=>$reason,'changed_by_user_id'=>$this->userId(),'created_at'=>date('Y-m-d H:i:s')]);}
    private function userId():int{return$this->actorUserId??(int)auth()->id();}
    private function number():string{return'STK-'.date('YmdHis').'-'.strtoupper(bin2hex(random_bytes(3)));}
}
