<?= $this->extend('layouts/panel') ?>
<?= $this->section('content') ?>
<?php $errors=session('errors')??[];$isEdit=$customer!==null; ?>
<div class="form-heading"><a class="back-link" href="<?= $isEdit?site_url('panel/musteriler/'.$customer['id']):site_url('panel/musteriler') ?>">← Geri dön</a><p class="page-lead"><?= $isEdit?'Firma ve iletişim bilgilerini güncelleyin.':'Yeni müşteri adayının temel bilgilerini kaydedin.' ?></p></div>
<?php if($errors): ?><div class="alert alert--error"><strong>Formu kontrol edin.</strong><span><?= esc($errors['duplicate']??$errors['contact']??$errors['form']??'Eksik veya hatalı alanlar bulunuyor.') ?></span></div><?php endif; ?>
<div class="duplicate-alert" data-duplicate-alert hidden></div>
<form method="post" action="<?= $isEdit?site_url('panel/musteriler/'.$customer['id'].'/duzenle'):site_url('panel/musteriler/yeni') ?>" class="employee-form customer-form" data-duplicate-url="<?= site_url('panel/musteriler/tekrar-kontrol') ?>" data-customer-id="<?= esc($customer['id']??'') ?>"><?= csrf_field() ?>
<section class="form-card"><div class="form-card__head"><span class="step-number">1</span><div><h2>Firma bilgileri</h2><p>Müşteriyi tanımlayan temel bilgiler.</p></div></div><div class="form-grid">
<label class="field"><span>Firma adı <b>*</b></span><input name="company_name" value="<?= esc(old('company_name',$customer['company_name']??'')) ?>" required maxlength="180" placeholder="Firma adı"><small><?= esc($errors['company_name']??'') ?></small></label><label class="field"><span>Resmî unvan</span><input name="official_title" value="<?= esc(old('official_title',$customer['official_title']??'')) ?>" maxlength="220" placeholder="Fatura unvanı"><small>Sipariş aşamasında tamamlanabilir.</small></label>
<label class="field"><span>İl <b>*</b></span><input name="city" value="<?= esc(old('city',$customer['city']??'')) ?>" required placeholder="İstanbul"><small><?= esc($errors['city']??'') ?></small></label><label class="field"><span>İlçe <b>*</b></span><input name="district" value="<?= esc(old('district',$customer['district']??'')) ?>" required placeholder="Ümraniye"><small><?= esc($errors['district']??'') ?></small></label>
<label class="field"><span>Firma e-postası</span><input type="email" name="email" value="<?= esc(old('email',$customer['email']??'')) ?>" placeholder="firma@ornek.com"><small><?= esc($errors['email']??'') ?></small></label><label class="field"><span>Durum</span><select name="status"><?php foreach($statuses as $key=>$label): ?><option value="<?= esc($key) ?>" <?= old('status',$customer['status']??'candidate')===$key?'selected':'' ?>><?= esc($label) ?></option><?php endforeach; ?></select></label>
</div></section>
<section class="form-card"><div class="form-card__head"><span class="step-number">2</span><div><h2>Yetkili kişi</h2><p>İlk kayıtta yetkili ve telefon zorunludur.</p></div></div><div class="form-grid"><label class="field"><span>Ad soyad <b>*</b></span><input name="contact_name" value="<?= esc(old('contact_name',$contact['full_name']??'')) ?>" required placeholder="Yetkili kişi"><small></small></label><label class="field"><span>Görevi</span><input name="contact_job_title" value="<?= esc(old('contact_job_title',$contact['job_title']??'')) ?>" placeholder="Satın alma sorumlusu"><small></small></label><label class="field"><span>Telefon <b>*</b></span><input name="contact_phone" value="<?= esc(old('contact_phone',$contact['phone']??'')) ?>" required inputmode="tel" placeholder="05xx xxx xx xx" data-duplicate-phone><small>Aynı numara için sistem uyarır.</small></label><label class="field"><span>E-posta</span><input type="email" name="contact_email" value="<?= esc(old('contact_email',$contact['email']??'')) ?>" placeholder="yetkili@firma.com"><small></small></label></div></section>
<section class="form-card"><div class="form-card__head"><span class="step-number">3</span><div><h2>Adres ve finans</h2><p>Daha sonra tamamlanabilecek işletme bilgileri.</p></div></div><div class="form-grid"><label class="field field--wide"><span>Açık adres</span><textarea name="address" rows="3" placeholder="Firma adresi"><?= esc(old('address',$customer['address']??'')) ?></textarea></label><label class="field"><span>Vergi dairesi</span><input name="tax_office" value="<?= esc(old('tax_office',$customer['tax_office']??'')) ?>"></label><label class="field"><span>Vergi numarası</span><input name="tax_number" value="<?= esc(old('tax_number',$customer['tax_number']??'')) ?>" inputmode="numeric" data-duplicate-tax><small>Aynı numara için sistem uyarır.</small></label><label class="field"><span>Vade günü <b>*</b></span><input type="number" name="payment_term_days" min="0" max="365" value="<?= esc(old('payment_term_days',$customer['payment_term_days']??30)) ?>" required></label><label class="field"><span>Borç sınırı</span><div class="input-suffix"><input name="credit_limit" inputmode="decimal" value="<?= esc(old('credit_limit',$customer['credit_limit']??'')) ?>"><em>₺</em></div></label><?php if($canAssign&&!$isEdit): ?><label class="field field--wide"><span>İlk sorumlu</span><select name="current_owner_employee_id"><option value="">Daha sonra ata</option><?php foreach($employees as $person): ?><option value="<?= esc($person['id']) ?>" <?= old('current_owner_employee_id')==$person['id']?'selected':'' ?>><?= esc($person['full_name']) ?></option><?php endforeach; ?></select><small>Saha personeli kendi açtığı müşteriye otomatik atanır.</small></label><?php endif; ?></div></section>
<div class="form-actions"><span></span><span></span><a class="button button--secondary" href="<?= site_url('panel/musteriler') ?>">Vazgeç</a><button class="button" type="submit"><?= $isEdit?'Değişiklikleri kaydet':'Müşteriyi kaydet' ?></button></div></form>
<?= $this->endSection() ?>
