<?= $this->extend('layouts/panel') ?>
<?= $this->section('content') ?>
<div class="page-actions"><p class="page-lead"><?= $canViewAll ? 'Müşteri portföyünü, sorumluları ve son işlemleri yönetin.' : 'Size atanan müşterileri ve görüşmelerinizi yönetin.' ?></p><?php if (auth()->user()?->can('customers.create')): ?><a class="button" href="<?= site_url('panel/musteriler/yeni') ?>"><span class="button__plus">+</span> Yeni müşteri</a><?php endif; ?></div>
<div class="stats-grid"><article class="stat-card"><span>Toplam müşteri</span><strong><?= esc($stats['total']) ?></strong><small>Görüntüleme alanınız</small></article><article class="stat-card"><span>Aktif müşteri</span><strong><?= esc($stats['active']) ?></strong><small class="text-success">Çalışılan firmalar</small></article><article class="stat-card"><span>Atama bekleyen</span><strong><?= esc($stats['unassigned']) ?></strong><small>Sorumlusu bulunmuyor</small></article></div>
<section class="panel-card">
<form class="filter-bar" method="get"><label class="search-field"><svg viewBox="0 0 24 24"><path d="M9.5 3a6.5 6.5 0 1 0 3.98 11.64L19.85 21 21 19.85l-6.36-6.37A6.5 6.5 0 0 0 9.5 3Zm0 2a4.5 4.5 0 1 1 0 9 4.5 4.5 0 0 1 0-9Z"/></svg><span class="sr-only">Müşteri ara</span><input type="search" name="q" value="<?= esc($search) ?>" placeholder="Firma, kod, yetkili veya telefon ara"></label><label><span class="sr-only">Durum</span><select name="durum"><option value="">Tüm durumlar</option><?php foreach ($statuses as $key=>$label): ?><option value="<?= esc($key) ?>" <?= $status===$key?'selected':'' ?>><?= esc($label) ?></option><?php endforeach; ?></select></label><?php if ($canViewAll): ?><label><span class="sr-only">Sorumlu</span><select name="sorumlu"><option value="">Tüm sorumlular</option><?php foreach ($employees as $person): ?><option value="<?= esc($person['id']) ?>" <?= $owner===$person['id']?'selected':'' ?>><?= esc($person['full_name']) ?></option><?php endforeach; ?></select></label><?php endif; ?><button class="button button--secondary" type="submit">Süz</button><?php if ($search||$status||$owner): ?><a class="text-link" href="<?= site_url('panel/musteriler') ?>">Temizle</a><?php endif; ?></form>
<?php if (!$customers): ?><div class="empty-state"><span>FM</span><h2>Müşteri bulunamadı</h2><p>Arama ölçütlerini değiştirin veya yeni müşteri ekleyin.</p></div><?php else: ?><div class="customer-grid"><?php foreach ($customers as $item): ?><a class="customer-card" href="<?= site_url('panel/musteriler/'.$item['id']) ?>"><div class="customer-card__top"><span class="company-avatar"><?= esc(mb_strtoupper(mb_substr($item['company_name'],0,1))) ?></span><div><h2><?= esc($item['company_name']) ?></h2><p><?= esc($item['customer_code']) ?> · <?= esc($item['city'].' / '.$item['district']) ?></p></div><span class="badge <?= $item['status']==='active'?'badge--success':'badge--neutral' ?>"><?= esc($statuses[$item['status']]??$item['status']) ?></span></div><dl><div><dt>Yetkili</dt><dd><?= esc($item['contact_name']??'—') ?></dd></div><div><dt>Telefon</dt><dd><?= esc($item['contact_phone']??'—') ?></dd></div><div><dt>Sorumlu</dt><dd><?= esc($item['owner_name']??'Atama bekliyor') ?></dd></div><div><dt>Son işlem</dt><dd><?= $item['last_activity_at']?esc(date('d.m.Y',strtotime($item['last_activity_at']))):'Henüz yok' ?></dd></div></dl><span class="customer-card__open">Müşteri ayrıntıları →</span></a><?php endforeach; ?></div><?php endif; ?>
</section>
<?= $this->endSection() ?>
