<?= $this->extend('layouts/panel') ?>
<?= $this->section('content') ?>
<?php $errors=session('errors')??[]; ?>
<div class="detail-heading">
    <div><a class="back-link" href="<?= site_url('panel/musteriler') ?>">← Müşteri listesi</a><p><span class="badge <?= $customer['status']==='active'?'badge--success':'badge--neutral' ?>"><?= esc($statuses[$customer['status']]??$customer['status']) ?></span> <span class="muted"><?= esc($customer['customer_code']) ?></span></p></div>
    <div class="action-group"><?php if($canCreateOrder): ?><a class="button button--secondary" href="<?= site_url('panel/siparisler/yeni?tur=quote&musteri='.$customer['id']) ?>">Yeni teklif</a><a class="button" href="<?= site_url('panel/siparisler/yeni?tur=order&musteri='.$customer['id']) ?>">Yeni sipariş</a><?php endif; ?><?php if(auth()->user()?->can('customers.create')): ?><a class="button button--secondary" href="<?= site_url('panel/musteriler/'.$customer['id'].'/duzenle') ?>">Bilgileri düzenle</a><?php endif; ?></div>
</div>
<?php if($errors): ?><div class="alert alert--error"><strong>İşlem tamamlanamadı.</strong><span><?= esc(reset($errors)) ?></span></div><?php endif; ?>
<div class="detail-grid"><div class="detail-main">
<section class="form-card info-card"><div class="section-heading-inline"><h2>Firma özeti</h2></div><dl class="info-list"><div><dt>Yetkili kişi</dt><dd><?= esc($contact['full_name']??'—') ?><small><?= esc($contact['job_title']??'') ?></small></dd></div><div><dt>Telefon</dt><dd><a href="tel:<?= esc($contact['phone']??'') ?>"><?= esc($contact['phone']??'—') ?></a></dd></div><div><dt>Konum</dt><dd><?= esc($customer['city'].' / '.$customer['district']) ?></dd></div><div><dt>Sorumlu</dt><dd><?= esc($customer['owner_name']??'Atama bekliyor') ?></dd></div><div><dt>Vade</dt><dd><?= esc($customer['payment_term_days']) ?> gün</dd></div><div><dt>Son işlem</dt><dd><?= $customer['last_activity_at']?esc(date('d.m.Y H:i',strtotime($customer['last_activity_at']))):'Henüz yok' ?></dd></div></dl><?php if($customer['address']): ?><div class="address-box"><span>Adres</span><p><?= nl2br(esc($customer['address'])) ?></p></div><?php endif; ?></section>
<section class="form-card"><div class="section-heading-inline"><div><h2>Teklifler ve siparişler</h2><p>Müşteriye ait satış belgeleri.</p></div><a class="text-link" href="<?= site_url('panel/siparisler?q='.rawurlencode($customer['company_name'])) ?>">Tümünü aç</a></div><div class="assignment-list"><?php if(!$salesDocuments): ?><p class="muted">Henüz teklif veya sipariş yok.</p><?php endif; ?><?php foreach(array_slice($salesDocuments,0,6) as $salesDocument): ?><a href="<?= site_url('panel/siparisler/'.$salesDocument['id']) ?>"><div><strong><?= esc($salesDocument['document_number']) ?></strong><span><?= $salesDocument['document_type']==='quote'?'Teklif':'Sipariş' ?> · <?= esc(date('d.m.Y',strtotime($salesDocument['created_at']))) ?></span><small><?= number_format((float)$salesDocument['grand_total'],2,',','.') ?> ₺</small></div></a><?php endforeach; ?></div></section>
<section class="form-card"><div class="section-heading-inline"><div><h2>Görüşmeler ve yapılacak işler</h2><p>Müşteriyle kurulan iletişimin geçmişi.</p></div></div><?php if($canAddActivity): ?><form class="activity-form" method="post" action="<?= site_url('panel/musteriler/'.$customer['id'].'/gorusme') ?>"><?= csrf_field() ?><select name="activity_type" aria-label="Görüşme türü"><?php foreach($activityTypes as $key=>$label): ?><option value="<?= esc($key) ?>"><?= esc($label) ?></option><?php endforeach; ?></select><input name="subject" required placeholder="Görüşme konusu"><input type="datetime-local" name="next_action_at" aria-label="Sonraki işlem tarihi"><textarea name="notes" rows="2" placeholder="Kısa not"></textarea><button class="button" type="submit">Görüşme ekle</button></form><?php endif; ?><div class="timeline"><?php if(!$activities): ?><p class="muted">Henüz görüşme kaydı yok.</p><?php endif; ?><?php foreach($activities as $activity): ?><article><i></i><div><span><?= esc($activityTypes[$activity['activity_type']]??$activity['activity_type']) ?> · <?= esc(date('d.m.Y H:i',strtotime($activity['happened_at']))) ?></span><h3><?= esc($activity['subject']) ?></h3><?php if($activity['notes']): ?><p><?= nl2br(esc($activity['notes'])) ?></p><?php endif; ?><?php if($activity['next_action_at']): ?><small>Sonraki işlem: <?= esc(date('d.m.Y H:i',strtotime($activity['next_action_at']))) ?></small><?php endif; ?></div></article><?php endforeach; ?></div></section>
</div><aside class="detail-aside"><?php if($canAssign): ?><section class="form-card compact-card"><h2>Sorumlu personel</h2><p class="muted">Müşteriyi başka personele devredin.</p><form method="post" action="<?= site_url('panel/musteriler/'.$customer['id'].'/sorumlu') ?>"><?= csrf_field() ?><label class="field"><span>Yeni sorumlu</span><select name="employee_id" required><option value="">Personel seçin</option><?php foreach($employees as $person): ?><option value="<?= esc($person['id']) ?>"><?= esc($person['full_name']) ?></option><?php endforeach; ?></select></label><label class="field"><span>Devir nedeni</span><textarea name="reason" rows="3" placeholder="Devir varsa nedeni zorunludur"></textarea></label><button class="button button--block" type="submit">Sorumluyu güncelle</button></form></section><?php endif; ?><section class="form-card compact-card"><h2>Atama geçmişi</h2><div class="assignment-list"><?php if(!$assignments): ?><p class="muted">Henüz atama yok.</p><?php endif; ?><?php foreach($assignments as $assignment): ?><div><strong><?= esc($assignment['employee_name']) ?></strong><span><?= esc(date('d.m.Y',strtotime($assignment['started_at']))) ?> — <?= $assignment['ended_at']?esc(date('d.m.Y',strtotime($assignment['ended_at']))):'Devam ediyor' ?></span><small><?= esc($assignment['reason']??'') ?></small></div><?php endforeach; ?></div></section></aside></div>
<?= $this->endSection() ?>
