<?php
declare(strict_types=1);
namespace App\Controllers\Panel;
use App\Controllers\BaseController;
use App\Libraries\AuditLogger;
use App\Models\PurchaseOrderItemModel;
use App\Models\PurchaseOrderModel;
use App\Models\StockCountItemModel;
use App\Models\StockCountModel;
use App\Models\SupplierModel;
use App\Models\WarehouseModel;
use App\Services\StockService;
use CodeIgniter\Exceptions\PageNotFoundException;
use CodeIgniter\HTTP\RedirectResponse;
use RuntimeException;
use Throwable;
class Inventory extends BaseController
{
    private const MOVEMENT_LABELS=['manual_in'=>'Serbest giriş','manual_out'=>'Serbest çıkış','customer_return'=>'Müşteri iadesi','supplier_return'=>'Tedarikçiye iade','adjustment'=>'Düzeltme','purchase_receipt'=>'Mal kabul','transfer_in'=>'Transfer girişi','transfer_out'=>'Transfer çıkışı','shipment'=>'Sevkiyat'];
    public function index():string
    {$this->require('stock.manage');$warehouseId=(int)$this->request->getGet('depo');$warehouses=$this->warehouses();if($warehouseId<=0)$warehouseId=(int)($warehouses[0]['id']??0);$db=db_connect();$balances=$db->table('product_variants pv')->select('pv.id AS variant_id,pv.sku,pv.size,pv.color,p.name AS product_name,p.critical_stock_level,pv.critical_stock_level AS variant_critical,COALESCE(sb.on_hand_quantity,0) AS on_hand_quantity,COALESCE(sb.reserved_quantity,0) AS reserved_quantity',false)->join('products p','p.id=pv.product_id')->join('stock_balances sb','sb.product_variant_id=pv.id AND sb.warehouse_id='.$warehouseId,'left')->where('pv.is_active',1)->where('p.track_stock',1)->where('p.is_active',1)->orderBy('p.name')->orderBy('pv.sku')->get()->getResultArray();foreach($balances as &$row){$row['available_quantity']=(float)$row['on_hand_quantity']-(float)$row['reserved_quantity'];$row['threshold']=$row['variant_critical']!==null?(float)$row['variant_critical']:(float)$row['critical_stock_level'];$row['is_critical']=$row['threshold']>0&&(float)$row['available_quantity']<=$row['threshold'];}unset($row);$movements=$db->table('stock_movements sm')->select('sm.*,w.name AS warehouse_name,pv.sku,p.name AS product_name,u.username,u.id AS user_id')->join('warehouses w','w.id=sm.warehouse_id')->join('product_variants pv','pv.id=sm.product_variant_id')->join('products p','p.id=pv.product_id')->join('users u','u.id=sm.created_by_user_id')->orderBy('sm.created_at','DESC')->limit(100)->get()->getResultArray();$fulfillmentOrders=$db->table('sales_documents sd')->select('sd.id,sd.document_number,sd.status,c.company_name,SUM(sdi.quantity-sdi.fulfilled_quantity) AS remaining',false)->join('customers c','c.id=sd.customer_id')->join('sales_document_items sdi','sdi.sales_document_id=sd.id')->where('sd.document_type','order')->whereIn('sd.status',['approved','procurement_waiting','reserved','partially_shipped'])->groupBy('sd.id,sd.document_number,sd.status,c.company_name')->orderBy('sd.created_at','DESC')->get()->getResultArray();return view('panel/inventory/index',['title'=>'Stok ve Depo | FORMMIX','pageTitle'=>'Stok ve depo','activeNav'=>'inventory','warehouses'=>$warehouses,'warehouseId'=>$warehouseId,'balances'=>$balances,'criticalCount'=>count(array_filter($balances,fn($r)=>$r['is_critical'])),'movements'=>$movements,'movementLabels'=>self::MOVEMENT_LABELS,'variants'=>$this->variants(),'fulfillmentOrders'=>$fulfillmentOrders,'canManageWarehouses'=>$this->can('warehouses.manage'),'canCount'=>$this->can('stock.count')]);}
    public function suppliers():string{$this->requirePurchaseAccess();return view('panel/inventory/suppliers',['title'=>'Tedarikçiler | FORMMIX','pageTitle'=>'Tedarikçiler','activeNav'=>'purchases','suppliers'=>(new SupplierModel())->orderBy('company_name')->findAll(),'canManage'=>$this->can('suppliers.manage')]);}
    public function storeSupplier():RedirectResponse{$this->require('suppliers.manage');$model=new SupplierModel();$data=['supplier_code'=>mb_strtoupper(trim((string)$this->request->getPost('supplier_code'))),'company_name'=>trim((string)$this->request->getPost('company_name')),'contact_name'=>trim((string)$this->request->getPost('contact_name'))?:null,'phone'=>trim((string)$this->request->getPost('phone'))?:null,'email'=>trim((string)$this->request->getPost('email'))?:null,'tax_number'=>trim((string)$this->request->getPost('tax_number'))?:null,'address'=>trim((string)$this->request->getPost('address'))?:null,'notes'=>trim((string)$this->request->getPost('notes'))?:null,'is_active'=>1,'created_by_user_id'=>auth()->id()];if(!$model->insert($data))return redirect()->back()->withInput()->with('errors',$model->errors());$id=(int)$model->getInsertID();(new AuditLogger())->record('supplier.created','supplier',$id,null,$data);return redirect()->back()->with('message','Tedarikçi kaydedildi.');}
    public function toggleSupplier(int $id):RedirectResponse{$this->require('suppliers.manage');$model=new SupplierModel();$row=$model->find($id);if(!$row)throw PageNotFoundException::forPageNotFound();$active=(int)!$row['is_active'];$model->update($id,['is_active'=>$active]);(new AuditLogger())->record('supplier.status_changed','supplier',$id,['is_active'=>$row['is_active']],['is_active'=>$active]);return redirect()->back()->with('message','Tedarikçi durumu güncellendi.');}
    public function storeWarehouse():RedirectResponse{$this->require('warehouses.manage');$model=new WarehouseModel();$data=['code'=>mb_strtoupper(trim((string)$this->request->getPost('code'))),'name'=>trim((string)$this->request->getPost('name')),'address'=>trim((string)$this->request->getPost('address'))?:null,'is_active'=>1];if(!$model->insert($data))return redirect()->back()->withInput()->with('errors',$model->errors());$id=(int)$model->getInsertID();(new AuditLogger())->record('warehouse.created','warehouse',$id,null,$data);return redirect()->back()->with('message','Depo tanımlandı.');}
    public function storeMovement():RedirectResponse{$this->require('stock.manage');$type=(string)$this->request->getPost('movement_type');$quantity=$this->decimal($this->request->getPost('quantity'));$reason=trim((string)$this->request->getPost('reason'));$warehouse=(int)$this->request->getPost('warehouse_id');$variant=(int)$this->request->getPost('product_variant_id');try{if($type==='transfer')(new StockService())->transfer($warehouse,(int)$this->request->getPost('target_warehouse_id'),$variant,$quantity,$reason);else{$sign=in_array($type,['manual_out','supplier_return'],true)?-1:1;if(!in_array($type,['manual_in','manual_out','customer_return','supplier_return'],true))throw new RuntimeException('Geçersiz stok hareketi.');(new StockService())->move($warehouse,$variant,$quantity*$sign,$type,$reason);}(new AuditLogger())->record('stock.movement_created','product_variant',$variant,null,['type'=>$type,'quantity'=>$quantity,'warehouse_id'=>$warehouse,'reason'=>$reason]);return redirect()->back()->with('message','Stok hareketi kaydedildi.');}catch(Throwable $e){return redirect()->back()->withInput()->with('errors',['movement'=>$e->getMessage()]);}}
    public function storeCount():RedirectResponse{$this->require('stock.count');$warehouse=(int)$this->request->getPost('warehouse_id');$variant=(int)$this->request->getPost('product_variant_id');$counted=$this->decimal($this->request->getPost('counted_quantity'));$reason=trim((string)$this->request->getPost('reason'));if($counted<0||$reason==='')return redirect()->back()->withInput()->with('errors',['count'=>'Sayım miktarı eksi olamaz ve gerekçe zorunludur.']);$service=new StockService();$balance=$service->balance($warehouse,$variant);if($counted<(float)$balance['reserved_quantity'])return redirect()->back()->withInput()->with('errors',['count'=>'Sayılan miktar ayrılmış stoktan az olamaz.']);$difference=$counted-(float)$balance['on_hand_quantity'];$db=db_connect();$db->transBegin();try{$model=new StockCountModel();$model->insert(['count_number'=>$this->number('SAY'),'warehouse_id'=>$warehouse,'status'=>'completed','reason'=>$reason,'counted_at'=>date('Y-m-d H:i:s'),'created_by_user_id'=>auth()->id()]);$id=(int)$model->getInsertID();$movement=null;if(abs($difference)>=0.0005)$movement=$service->move($warehouse,$variant,$difference,'adjustment','Sayım farkı: '.$reason,'stock_count',$id);(new StockCountItemModel())->insert(['stock_count_id'=>$id,'product_variant_id'=>$variant,'system_quantity'=>$balance['on_hand_quantity'],'counted_quantity'=>$counted,'difference_quantity'=>$difference,'stock_movement_id'=>$movement,'created_at'=>date('Y-m-d H:i:s')]);if(!$db->transStatus())throw new RuntimeException('Sayım kaydedilemedi.');$db->transCommit();(new AuditLogger())->record('stock.count_completed','stock_count',$id,null,['variant_id'=>$variant,'system'=>$balance['on_hand_quantity'],'counted'=>$counted,'difference'=>$difference,'reason'=>$reason]);return redirect()->back()->with('message','Sayım ve fark kaydı tamamlandı.');}catch(Throwable $e){$db->transRollback();return redirect()->back()->withInput()->with('errors',['count'=>$e->getMessage()]);}}
    public function purchases():string{$this->requirePurchaseAccess();$orders=(new PurchaseOrderModel())->select('purchase_orders.*,suppliers.company_name,warehouses.name AS warehouse_name')->join('suppliers','suppliers.id=purchase_orders.supplier_id')->join('warehouses','warehouses.id=purchase_orders.warehouse_id')->orderBy('purchase_orders.created_at','DESC')->findAll();return view('panel/inventory/purchases',['title'=>'Alış Siparişleri | FORMMIX','pageTitle'=>'Alış siparişleri','activeNav'=>'purchases','orders'=>$orders,'canCreate'=>$this->can('purchases.create'),'canViewCost'=>$this->can('products.view-cost')]);}
    public function createPurchase():string{$this->require('purchases.create');return view('panel/inventory/purchase_form',['title'=>'Yeni Alış Siparişi | FORMMIX','pageTitle'=>'Yeni alış siparişi','activeNav'=>'purchases','suppliers'=>(new SupplierModel())->where('is_active',1)->orderBy('company_name')->findAll(),'warehouses'=>$this->warehouses(),'variants'=>$this->variants(true)]);}
    public function storePurchase():RedirectResponse{$this->require('purchases.create');$supplier=(new SupplierModel())->where('is_active',1)->find((int)$this->request->getPost('supplier_id'));$warehouse=(new WarehouseModel())->where('is_active',1)->find((int)$this->request->getPost('warehouse_id'));$input=json_decode((string)$this->request->getPost('items_json'),true);if(!$supplier||!$warehouse||!is_array($input)||$input===[])return redirect()->back()->withInput()->with('errors',['form'=>'Tedarikçi, depo ve en az bir ürün satırı zorunludur.']);$variants=array_column($this->variants(true),null,'variant_id');$items=[];$subtotal=0.0;foreach($input as $row){$variantId=(int)($row['product_variant_id']??0);$qty=$this->decimal($row['quantity']??0);$cost=$this->decimal($row['unit_cost']??0);if(!isset($variants[$variantId])||$qty<=0||$cost<0)return redirect()->back()->withInput()->with('errors',['form'=>'Ürün satırlarından biri geçersiz.']);$variant=$variants[$variantId];$items[]=['product_variant_id'=>$variantId,'sku_snapshot'=>$variant['sku'],'product_name_snapshot'=>$variant['product_name'],'ordered_quantity'=>$qty,'received_quantity'=>0,'unit_cost'=>$cost];$subtotal+=round($qty*$cost,2);}$db=db_connect();$db->transBegin();try{$model=new PurchaseOrderModel();$data=['order_number'=>$this->number('ALS'),'supplier_id'=>$supplier['id'],'warehouse_id'=>$warehouse['id'],'status'=>'ordered','order_date'=>$this->dateOrToday((string)$this->request->getPost('order_date')),'expected_date'=>$this->dateOrNull((string)$this->request->getPost('expected_date')),'currency'=>'TRY','subtotal'=>$subtotal,'notes'=>trim((string)$this->request->getPost('notes'))?:null,'created_by_user_id'=>auth()->id()];if(!$model->insert($data))throw new RuntimeException(implode(' ',$model->errors()));$id=(int)$model->getInsertID();foreach($items as $item){$item['purchase_order_id']=$id;(new PurchaseOrderItemModel())->insert($item);}if(!$db->transStatus())throw new RuntimeException('Alış siparişi kaydedilemedi.');$db->transCommit();(new AuditLogger())->record('purchase.created','purchase_order',$id,null,$data);return redirect()->to(site_url('panel/alislar/'.$id))->with('message','Alış siparişi oluşturuldu.');}catch(Throwable $e){$db->transRollback();return redirect()->back()->withInput()->with('errors',['form'=>$e->getMessage()]);}}
    public function showPurchase(int $id):string{$this->requirePurchaseAccess();$order=(new PurchaseOrderModel())->select('purchase_orders.*,suppliers.company_name,warehouses.name AS warehouse_name')->join('suppliers','suppliers.id=purchase_orders.supplier_id')->join('warehouses','warehouses.id=purchase_orders.warehouse_id')->find($id);if(!$order)throw PageNotFoundException::forPageNotFound();return view('panel/inventory/purchase_show',['title'=>$order['order_number'].' | FORMMIX','pageTitle'=>$order['order_number'],'activeNav'=>'purchases','order'=>$order,'items'=>(new PurchaseOrderItemModel())->where('purchase_order_id',$id)->findAll(),'canReceive'=>$this->can('purchases.receive')&&in_array($order['status'],['ordered','partial'],true),'canViewCost'=>$this->can('products.view-cost')]);}
    public function receivePurchase(int $id):RedirectResponse{$this->require('purchases.receive');$order=(new PurchaseOrderModel())->find($id);if(!$order||!in_array($order['status'],['ordered','partial'],true))throw PageNotFoundException::forPageNotFound();$posted=$this->request->getPost('receive');if(!is_array($posted))return redirect()->back()->with('errors',['receive'=>'Mal kabul miktarı girin.']);$items=(new PurchaseOrderItemModel())->where('purchase_order_id',$id)->findAll();$db=db_connect();$db->transBegin();$received=0.0;try{foreach($items as $item){$qty=$this->decimal($posted[$item['id']]??0);$remaining=(float)$item['ordered_quantity']-(float)$item['received_quantity'];if($qty<0||$qty>$remaining+0.0001)throw new RuntimeException($item['sku_snapshot'].' için kabul miktarı kalan miktarı aşıyor.');if($qty<=0)continue;(new StockService())->move((int)$order['warehouse_id'],(int)$item['product_variant_id'],$qty,'purchase_receipt','Alış mal kabulü '.$order['order_number'],'purchase_order',$id);(new PurchaseOrderItemModel())->update($item['id'],['received_quantity'=>(float)$item['received_quantity']+$qty]);$received+=$qty;}if($received<=0)throw new RuntimeException('En az bir ürün için kabul miktarı girin.');$remainingRow=(new PurchaseOrderItemModel())->select('SUM(ordered_quantity-received_quantity) AS remaining',false)->where('purchase_order_id',$id)->first();$status=(float)($remainingRow['remaining']??0)>0?'partial':'received';(new PurchaseOrderModel())->update($id,['status'=>$status]);if(!$db->transStatus())throw new RuntimeException('Mal kabul kaydedilemedi.');$db->transCommit();(new AuditLogger())->record('purchase.received','purchase_order',$id,['status'=>$order['status']],['status'=>$status,'quantity'=>$received]);return redirect()->back()->with('message','Mal kabul kaydedildi ve stok artırıldı.');}catch(Throwable $e){$db->transRollback();return redirect()->back()->with('errors',['receive'=>$e->getMessage()]);}}
    public function reserveOrder(int $id):RedirectResponse{$this->require('orders.fulfill');try{$result=(new StockService())->reserveOrder($id,(int)$this->request->getPost('warehouse_id'));return redirect()->back()->with('message',$result['missing']>0?'Mevcut stok ayrıldı; eksik miktar tedarik bekliyor.':'Sipariş stoğu tamamen ayrıldı.');}catch(Throwable $e){return redirect()->back()->with('errors',['stock'=>$e->getMessage()]);}}
    public function shipOrder(int $id):RedirectResponse{$this->require('orders.fulfill');try{(new StockService())->shipReserved($id,trim((string)$this->request->getPost('reason')));return redirect()->back()->with('message','Ayrılmış ürünler sevk edildi; stok hareketi oluştu.');}catch(Throwable $e){return redirect()->back()->with('errors',['stock'=>$e->getMessage()]);}}
    private function variants(bool $withCost=false):array{$select='pv.id AS variant_id,pv.sku,pv.size,pv.color,p.name AS product_name';if($withCost)$select.=',COALESCE(pv.cost_price_override,p.cost_price) AS unit_cost';return db_connect()->table('product_variants pv')->select($select,false)->join('products p','p.id=pv.product_id')->where('pv.is_active',1)->where('p.is_active',1)->orderBy('p.name')->orderBy('pv.sku')->get()->getResultArray();}
    private function warehouses():array{return(new WarehouseModel())->where('is_active',1)->orderBy('name')->findAll();}
    private function can(string $permission):bool{return auth()->user()?->can($permission)??false;}
    private function require(string $permission):void{if(!$this->can($permission))throw PageNotFoundException::forPageNotFound();}
    private function requirePurchaseAccess():void{if(!$this->can('purchases.manage')&&!$this->can('purchases.create')&&!$this->can('purchases.receive'))throw PageNotFoundException::forPageNotFound();}
    private function decimal(mixed $value):float{$value=str_replace(',','.',trim((string)$value));return is_numeric($value)?round((float)$value,3):0.0;}
    private function dateOrNull(string $value):?string{return preg_match('/^\d{4}-\d{2}-\d{2}$/',$value)?$value:null;}
    private function dateOrToday(string $value):string{return$this->dateOrNull($value)??date('Y-m-d');}
    private function number(string $prefix):string{return$prefix.'-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));}
}
