<?= $this->extend('layouts/panel') ?>
<?= $this->section('content') ?>
<div class="page-actions"><div><p class="page-lead">Göreviniz için temel iş akışları ve manuel kabul testi adımları.</p></div></div>
<section class="release-boundary"><div><span class="eyebrow">Güvenli kullanım</span><h2>Her kullanıcı kendi hesabıyla çalışır</h2><p>Parolanızı, e-posta doğrulama bağlantısını veya müşteri verisini paylaşmayın. Beklenmeyen sonuçta işlemi tekrarlamadan belge numarası ve yaptığınız adımlarla sorunu yöneticinize bildirin.</p></div></section>
<div class="guide-grid">
<?php if ($showOwner): ?><section class="form-card guide-card"><span class="step-number">1</span><h2>İşletme sahibi</h2><ol><li>Personel–kullanıcı bağlantılarını ve görevleri kontrol edin.</li><li>Onay bekleyen ve yüksek indirimli siparişleri inceleyin.</li><li>Maliyet ve brüt kârın yalnızca yetkili görevlerde göründüğünü doğrulayın.</li><li>Yayına hazırlık ekranında cihaz, kullanıcı ve sonucu not edin.</li><li>Kritik sorun açıkken veya geri dönüş denenmeden yazılı onay vermeyin.</li></ol></section><?php endif; ?>
<?php if ($showSales): ?><section class="form-card guide-card"><span class="step-number">2</span><h2>Satış yöneticisi</h2><ol><li>Müşteri sorumlusu atama ve gerekçeli devir işlemini deneyin.</li><li>Saha siparişini onaylayın; kendi siparişinizi onaylayamadığınızı kontrol edin.</li><li>Yetki üzerindeki indirimin doğru onaya gittiğini doğrulayın.</li><li>Personel/tarih filtreli satış raporlarını kontrol edin.</li><li>Alış maliyetinin görünmediğini doğrulayın.</li></ol></section><?php endif; ?>
<?php if ($showField): ?><section class="form-card guide-card"><span class="step-number">3</span><h2>Saha personeli</h2><ol><li>Yalnızca kendi müşterilerinizi görebildiğinizi kontrol edin.</li><li>Telefondan teklif ve sipariş taslağı oluşturun.</li><li>Bağlantıyı kesip taslağın korunduğunu, dönüşte tek kayıt oluştuğunu kontrol edin.</li><li>İndirim sınırı üzerindeki siparişin onaya düştüğünü doğrulayın.</li><li>Başka personele ait kayda erişemediğinizi kontrol edin.</li></ol></section><?php endif; ?>
<?php if ($showAccounting): ?><section class="form-card guide-card"><span class="step-number">4</span><h2>Muhasebe</h2><p class="muted">Cari, tahsilat ve ödeme Adım 7 atlandığı için bu sürümde bulunmaz.</p><ol><li>Satış ve alış belgelerini görüntüleyin.</li><li>Maliyet ve temel brüt kârlılık raporunu kontrol edin.</li><li>Yetkisiz ürün, kullanıcı ve onay işlemlerinin reddedildiğini doğrulayın.</li><li>CSV/XLSX çıktısının ekran filtresini koruduğunu kontrol edin.</li></ol></section><?php endif; ?>
<?php if ($showWarehouse): ?><section class="form-card guide-card"><span class="step-number">5</span><h2>Depo</h2><ol><li>Kısmi ve tam mal kabul yapın.</li><li>Siparişe stok ayırıp eksikte tedarik bekliyor durumunu kontrol edin.</li><li>Kısmi/tam sevkiyat sonrası stok bakiyelerini karşılaştırın.</li><li>İade, transfer ve gerekçeli sayım farkını deneyin.</li><li>Eksi stok işleminin reddedildiğini ve maliyetin görünmediğini doğrulayın.</li></ol></section><?php endif; ?>
<section class="form-card guide-card"><span class="step-number">!</span><h2>Sorun bildirimi</h2><ul><li>Görev ve kullanılan cihaz</li><li>Sayfa, işlem ve varsa belge numarası</li><li>Beklenen ve gerçekleşen sonuç</li><li>Tekrar etme adımları</li></ul><p class="muted">Parola veya başka bir gizli bilgiyi sorun notuna yazmayın.</p></section>
</div>
<?= $this->endSection() ?>
