import { useQuery } from '@tanstack/react-query';
import { StyleSheet, Text, View } from 'react-native';
import { api } from '@/api';
import { useAuth } from '@/auth';
import { Card, Header, Loading, Screen } from '@/components';
import { colors } from '@/theme';
type Bootstrap={data:{employee:{name:string};open_order_count:number;unread_notification_count:number;dashboard_metrics?:{monthNetSales?:number};features:Record<string,boolean>}};
export default function Home(){const{session}=useAuth();const query=useQuery({queryKey:['bootstrap'],queryFn:()=>api<Bootstrap>('/bootstrap')});if(query.isLoading)return<Loading/>;const d=query.data?.data;return <Screen><Header title={`Merhaba, ${session?.user.employee.name.split(' ')[0]}`} subtitle="Bugunku calisma alaniniz"/><View style={styles.grid}><Card><Text style={styles.number}>{d?.open_order_count??0}</Text><Text style={styles.label}>Acik siparis</Text></Card><Card><Text style={styles.number}>{d?.unread_notification_count??0}</Text><Text style={styles.label}>Yeni bildirim</Text></Card></View>{d?.dashboard_metrics?.monthNetSales!==undefined?<Card><Text style={styles.label}>Bu ay satis</Text><Text style={styles.money}>{new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(d.dashboard_metrics.monthNetSales)}</Text></Card>:null}<Card><Text style={styles.cardTitle}>Guvenli mobil calisma</Text><Text style={styles.note}>Taslaklar cihazda sifreli saklanir. Cevrimdisi islemler siz Senkronize et demeden merkeze gonderilmez.</Text></Card></Screen>}
const styles=StyleSheet.create({grid:{flexDirection:'row',gap:12},number:{fontSize:30,fontWeight:'800',color:colors.orange},label:{color:colors.muted},money:{fontSize:24,fontWeight:'800',color:colors.navy},cardTitle:{fontSize:17,fontWeight:'700',color:colors.navy},note:{color:colors.muted,lineHeight:21}});
