import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import * as Crypto from 'expo-crypto';
import { router, useLocalSearchParams } from 'expo-router';
import { Alert, StyleSheet, Text } from 'react-native';
import { api, ApiError } from '@/api';
import { Button, Card, Header, Loading, Screen } from '@/components';
import { colors } from '@/theme';
type Detail={data:{id:number;document_number:string;document_type:'quote'|'order';status:string;company_name?:string;grand_total:number;subtotal:number;discount_total:number;tax_total:number;created_by_user_id:number;items:Array<{id:number;product_name_snapshot:string;variant_snapshot:string;quantity:number;discount_percent:number;line_total:number}>;history:Array<{id:number;new_status:string;reason?:string;created_at:string}>}};
export default function SaleDetail(){const{id}=useLocalSearchParams<{id:string}>();const client=useQueryClient();const query=useQuery({queryKey:['sales-document',id],queryFn:()=>api<Detail>(`/sales-documents/${id}`)});const action=useMutation({mutationFn:async(kind:'finalize'|'convert-to-order')=>api<{data:{id:number}}>(`/sales-documents/${id}/${kind}`,{method:'POST',body:'{}',idempotencyKey:kind==='convert-to-order'?Crypto.randomUUID():undefined}),onSuccess:async(response)=>{await client.invalidateQueries({queryKey:['sales-documents']});if(response.data.id!==Number(id))router.replace(`/sales/${response.data.id}`);else await query.refetch();},onError:error=>Alert.alert('Islem tamamlanamadi',error instanceof ApiError?error.message:'Baglanti kurulamadi.')});if(query.isLoading)return<Loading/>;const d=query.data?.data;if(!d)return<Screen><Text>Belge bulunamadi.</Text></Screen>;return <Screen><Header title={d.document_number} subtitle={`${d.document_type==='quote'?'Teklif':'Siparis'} - ${d.status}`}/><Card><Text style={styles.company}>{d.company_name||'Musteri'}</Text><Text style={styles.total}>{new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(Number(d.grand_total))}</Text><Text style={styles.muted}>Ara toplam {d.subtotal} - indirim {d.discount_total} - vergi {d.tax_total}</Text></Card>{d.items.map(item=><Card key={item.id}><Text style={styles.title}>{item.product_name_snapshot}</Text><Text style={styles.muted}>{item.variant_snapshot} - {item.quantity} adet - %{item.discount_percent}</Text><Text style={styles.price}>{new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(Number(item.line_total))}</Text></Card>)}{d.document_type==='quote'&&d.status==='draft'?<Button title="Teklifi kesinlestir" onPress={()=>action.mutate('finalize')} loading={action.isPending}/>:null}{d.document_type==='quote'&&d.status==='approved'?<Button title="Siparis taslagina donustur" onPress={()=>action.mutate('convert-to-order')} loading={action.isPending}/>:null}<Text style={styles.section}>Durum gecmisi</Text>{d.history.map(row=><Card key={row.id}><Text style={styles.title}>{row.new_status}</Text><Text style={styles.muted}>{new Date(row.created_at).toLocaleString('tr-TR')} {row.reason?`- ${row.reason}`:''}</Text></Card>)}</Screen>}
const styles=StyleSheet.create({company:{fontSize:18,fontWeight:'800',color:colors.navy},total:{fontSize:25,fontWeight:'800',color:colors.orange},title:{fontWeight:'800',color:colors.navy},price:{fontWeight:'800',color:colors.orange},muted:{color:colors.muted},section:{fontSize:20,fontWeight:'800',color:colors.navy}});
