import { useQuery, useQueryClient } from '@tanstack/react-query';
import * as Crypto from 'expo-crypto';
import { router } from 'expo-router';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useMemo, useState } from 'react';
import { api, ApiError } from '@/api';
import { cachedApi } from '@/cachedApi';
import { Button, Card, Field, Header, Loading, Screen } from '@/components';
import { queue } from '@/outbox';
import { colors } from '@/theme';
import type { Customer, Product, ProductVariant } from '@/types';
type Employee={id:number;name:string};
type Line={product_id:number;product_variant_id:number;name:string;variant:string;quantity:number;discount_percent:number;expected_unit_price:number;tax_rate:number};
function Choices<T extends {id:number}>({items,value,label,onSelect}:{items:T[];value:number;label(item:T):string;onSelect(id:number):void}){return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.choices}>{items.map(item=><Pressable key={item.id} onPress={()=>onSelect(item.id)} style={[styles.choice,value===item.id&&styles.choiceSelected]}><Text style={[styles.choiceText,value===item.id&&styles.choiceTextSelected]} numberOfLines={1}>{label(item)}</Text></Pressable>)}</ScrollView>}
export default function NewSale(){const client=useQueryClient();const customers=useQuery({queryKey:['customers','sale'],queryFn:()=>cachedApi<{data:Customer[]}>('sale-customers','/customers?per_page=100')});const products=useQuery({queryKey:['products','sale'],queryFn:()=>cachedApi<{data:Product[]}>('sale-products','/products?per_page=100')});const employees=useQuery({queryKey:['employees'],queryFn:()=>api<{data:Employee[]}>('/employees')});const[type,setType]=useState<'quote'|'order'>('quote');const[customerId,setCustomerId]=useState(0);const[productId,setProductId]=useState(0);const[variantId,setVariantId]=useState(0);const[quantity,setQuantity]=useState('1');const[discount,setDiscount]=useState('0');const[lines,setLines]=useState<Line[]>([]);const[delivery,setDelivery]=useState('');const[notes,setNotes]=useState('');const[preparation,setPreparation]=useState(0);const[design,setDesign]=useState(0);const[print,setPrint]=useState(0);const[saving,setSaving]=useState(false);const product=products.data?.data.find(p=>p.id===productId);const variants=product?.variants??[];const total=useMemo(()=>lines.reduce((sum,line)=>sum+line.quantity*line.expected_unit_price*(1-line.discount_percent/100)*(1+line.tax_rate/100),0),[lines]);if(customers.isLoading||products.isLoading||employees.isLoading)return<Loading/>;
async function addLine(){const selectedProduct=products.data?.data.find(p=>p.id===productId);const selectedVariant=selectedProduct?.variants.find(v=>v.id===variantId);if(!customerId||!selectedProduct||!selectedVariant){Alert.alert('Eksik secim','Musteri, urun ve varyant secin.');return;}let unitPrice=Number(selectedVariant.list_price_override||selectedProduct.list_price);let taxRate=Number(selectedProduct.tax_rate);try{const response=await api<{data:{unit_price:number;tax_rate:number}}>(`/products/${selectedProduct.id}/price?customer_id=${customerId}&variant_id=${selectedVariant.id}`);unitPrice=Number(response.data.unit_price);taxRate=Number(response.data.tax_rate);}catch(error){if(error instanceof ApiError&&error.status>0){Alert.alert('Fiyat alinamadi',error.message);return;}}setLines(current=>[...current,{product_id:selectedProduct.id,product_variant_id:selectedVariant.id,name:selectedProduct.name,variant:[selectedVariant.size,selectedVariant.color].filter(Boolean).join(' / ')||selectedVariant.sku,quantity:Math.max(.001,Number(quantity)||1),discount_percent:Math.max(0,Number(discount)||0),expected_unit_price:unitPrice,tax_rate:taxRate}]);}
async function save(intent:'draft'|'submit'){if(!customerId||!lines.length){Alert.alert('Eksik bilgi','Musteri ve en az bir urun satiri zorunludur.');return;}if(type==='order'&&intent==='submit'&&(!delivery.trim()||!preparation||!design||!print)){Alert.alert('Siparis tamamlanamadi','Teslimat adresi ile hazirlama, tasarim ve baski personellerini secin.');return;}const payload={document_type:type,intent,customer_id:customerId,delivery_address:delivery,notes,preparation_employee_id:preparation||null,design_employee_id:design||null,print_employee_id:print||null,items:lines.map(({name,variant,tax_rate,...line})=>line)};setSaving(true);const key=Crypto.randomUUID();try{const response=await api<{data:{id:number}}>('/sales-documents',{method:'POST',body:JSON.stringify(payload),idempotencyKey:key});await client.invalidateQueries({queryKey:['sales-documents']});router.replace(`/sales/${response.data.id}`);}catch(error){if(error instanceof ApiError&&error.status>0){Alert.alert(error.code,error.message);return;}await queue('sales_document.create','POST','/sales-documents',payload);Alert.alert('Taslak cihazda saklandi','Baglanti geldiginde Daha fazla > Senkronize et ile merkeze gonderebilirsiniz.');router.back();}finally{setSaving(false);}}
return <Screen><Header title="Yeni teklif / siparis"/><View style={styles.row}><Button title="Teklif" secondary={type!=='quote'} onPress={()=>setType('quote')}/><Button title="Siparis" secondary={type!=='order'} onPress={()=>setType('order')}/></View><Text style={styles.label}>Musteri</Text><Choices items={customers.data?.data??[]} value={customerId} label={item=>item.company_name} onSelect={setCustomerId}/><Text style={styles.label}>Urun</Text><Choices items={products.data?.data??[]} value={productId} label={item=>item.name} onSelect={id=>{setProductId(id);setVariantId(0);}}/>{product?<><Text style={styles.label}>Varyant</Text><Choices items={variants} value={variantId} label={(item:ProductVariant)=>[item.size,item.color].filter(Boolean).join(' / ')||item.sku} onSelect={setVariantId}/></>:null}<View style={styles.row}><View style={styles.flex}><Field label="Miktar" keyboardType="decimal-pad" value={quantity} onChangeText={setQuantity}/></View><View style={styles.flex}><Field label="Indirim %" keyboardType="decimal-pad" value={discount} onChangeText={setDiscount}/></View></View><Button title="Urun satiri ekle" secondary onPress={addLine}/>{lines.map((line,index)=><Card key={`${line.product_variant_id}-${index}`}><Text style={styles.lineTitle}>{line.name}</Text><Text style={styles.muted}>{line.variant} - {line.quantity} adet - %{line.discount_percent}</Text><Text style={styles.price}>{new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(line.quantity*line.expected_unit_price)}</Text><Button title="Satiri sil" secondary onPress={()=>setLines(current=>current.filter((_,i)=>i!==index))}/></Card>)}<Card><Text style={styles.total}>Tahmini toplam: {new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(total)}</Text><Text style={styles.muted}>Kesin fiyat ve vergi sunucuda yeniden hesaplanir.</Text></Card><Field label="Teslimat adresi" value={delivery} onChangeText={setDelivery} multiline/><Field label="Notlar" value={notes} onChangeText={setNotes} multiline/>{type==='order'?<><Text style={styles.label}>Hazirlama personeli</Text><Choices items={employees.data?.data??[]} value={preparation} label={item=>item.name} onSelect={setPreparation}/><Text style={styles.label}>Tasarim personeli</Text><Choices items={employees.data?.data??[]} value={design} label={item=>item.name} onSelect={setDesign}/><Text style={styles.label}>Baski personeli</Text><Choices items={employees.data?.data??[]} value={print} label={item=>item.name} onSelect={setPrint}/></>:null}<Button title="Taslak kaydet" secondary onPress={()=>save('draft')} loading={saving}/>{type==='order'?<Button title="Siparisi olustur" onPress={()=>save('submit')} loading={saving}/>:null}</Screen>}
const styles=StyleSheet.create({row:{flexDirection:'row',gap:8},flex:{flex:1},choices:{gap:8,paddingVertical:2},choice:{height:48,maxWidth:190,justifyContent:'center',paddingHorizontal:14,borderRadius:8,borderWidth:1,borderColor:colors.border,backgroundColor:'#fff'},choiceSelected:{backgroundColor:colors.navy,borderColor:colors.navy},choiceText:{color:colors.text,fontWeight:'600'},choiceTextSelected:{color:'#fff'},label:{fontWeight:'800',color:colors.navy},lineTitle:{fontWeight:'800',color:colors.navy,fontSize:16},muted:{color:colors.muted},price:{color:colors.orange,fontWeight:'800'},total:{color:colors.navy,fontWeight:'800',fontSize:19}});
