import type { PropsWithChildren, ReactNode } from 'react';
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps } from 'react-native';
import { colors, radius, spacing } from './theme';

export function Screen({ children, scroll = true }: PropsWithChildren<{ scroll?: boolean }>) {
  const content = scroll ? <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">{children}</ScrollView> : <View style={styles.content}>{children}</View>;
  return <SafeAreaView style={styles.safe}>{content}</SafeAreaView>;
}
export function Header({ title, subtitle, action }: { title: string; subtitle?: string; action?: ReactNode }) { return <View style={styles.header}><View style={{flex:1}}><Text style={styles.title}>{title}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}</View>{action}</View>; }
export function Card({ children }: PropsWithChildren) { return <View style={styles.card}>{children}</View>; }
export function Button({ title, onPress, loading, secondary=false, disabled=false }: { title:string; onPress():void; loading?:boolean; secondary?:boolean; disabled?:boolean }) { return <Pressable accessibilityRole="button" disabled={disabled||loading} onPress={onPress} style={({pressed})=>[styles.button,secondary&&styles.buttonSecondary,(pressed||disabled)&&{opacity:.65}]}>{loading?<ActivityIndicator color={secondary?colors.navy:'#fff'}/>:<Text style={[styles.buttonText,secondary&&{color:colors.navy}]}>{title}</Text>}</Pressable>; }
export function Field({ label, error, ...props }: TextInputProps & {label:string;error?:string}) { return <View style={{gap:6}}><Text style={styles.label}>{label}</Text><TextInput placeholderTextColor={colors.muted} {...props} style={[styles.input,props.multiline&&{minHeight:96,textAlignVertical:'top'},error&&{borderColor:colors.danger}]} />{error?<Text style={styles.error}>{error}</Text>:null}</View>; }
export function Empty({ text }: {text:string}) { return <Card><Text style={styles.empty}>{text}</Text></Card>; }
export function Loading() { return <View style={styles.center}><ActivityIndicator size="large" color={colors.orange}/><Text style={styles.subtitle}>Yukleniyor...</Text></View>; }

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.md,gap:spacing.md,flexGrow:1},header:{flexDirection:'row',alignItems:'center',gap:spacing.md,marginVertical:spacing.sm},title:{fontSize:27,fontWeight:'800',color:colors.navy},subtitle:{fontSize:14,color:colors.muted,marginTop:4},card:{backgroundColor:colors.card,borderRadius:radius.md,padding:spacing.md,borderWidth:1,borderColor:colors.border,gap:spacing.sm},button:{minHeight:48,borderRadius:radius.sm,backgroundColor:colors.orange,paddingHorizontal:spacing.md,alignItems:'center',justifyContent:'center'},buttonSecondary:{backgroundColor:colors.card,borderWidth:1,borderColor:colors.navy},buttonText:{color:'#fff',fontSize:16,fontWeight:'700'},label:{fontSize:14,fontWeight:'700',color:colors.text},input:{minHeight:48,borderRadius:radius.sm,borderWidth:1,borderColor:colors.border,backgroundColor:'#fff',paddingHorizontal:14,color:colors.text,fontSize:16},error:{color:colors.danger,fontSize:13},empty:{color:colors.muted,textAlign:'center',padding:spacing.lg},center:{flex:1,alignItems:'center',justifyContent:'center',gap:spacing.md}});
