import { useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Text } from 'react-native';
import { api, ApiError } from './api';
import { Button, Card, ChoiceChips, Field, Header, Screen, SectionTitle, Toggle } from './components';
import { colors } from './theme';

export type EmployeeEdit={id:number;user_id?:number;employee_code:string;full_name:string;phone?:string;max_discount_percent:number;can_collect_payment:number;is_active:number;role?:string;updated_at:string};
const roles=[{id:'sales_manager',name:'Satış yöneticisi'},{id:'field_sales',name:'Saha personeli'},{id:'accounting',name:'Muhasebe'},{id:'warehouse',name:'Depo'}];
export function EmployeeForm({employee}:{employee?:EmployeeEdit}){const client=useQueryClient();const[code,setCode]=useState(employee?.employee_code??'');const[name,setName]=useState(employee?.full_name??'');const[phone,setPhone]=useState(employee?.phone??'');const[discount,setDiscount]=useState(String(employee?.max_discount_percent??0));const[collect,setCollect]=useState(Boolean(employee?.can_collect_payment));const[active,setActive]=useState(employee?Boolean(employee.is_active):true);const[createAccount,setCreateAccount]=useState(!employee);const[role,setRole]=useState(employee?.role??'field_sales');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[saving,setSaving]=useState(false);
async function save(){if(!code.trim()||!name.trim()){Alert.alert('Eksik bilgi','Personel kodu ve ad soyad zorunludur.');return;}const payload:Record<string,unknown>={employee_code:code,full_name:name,phone,max_discount_percent:Number(discount)||0,can_collect_payment:collect,is_active:active};if(employee)payload.expected_updated_at=employee.updated_at;if(createAccount||employee?.user_id){payload.account_user_id=employee?.user_id?String(employee.user_id):'new';payload.role=role;if(!employee?.user_id){payload.login_email=email;payload.login_password=password;}else if(password)payload.login_password=password;}setSaving(true);try{const result=await api<{data:{id:number}}>(employee?`/employees/manage/${employee.id}`:'/employees/manage',{method:employee?'PUT':'POST',body:JSON.stringify(payload)});await client.invalidateQueries({queryKey:['employees-manage']});router.replace(`/employee/${result.data.id}` as never);}catch(e){Alert.alert('Kaydedilemedi',e instanceof ApiError?e.message:'Bağlantı kurulamadı.');}finally{setSaving(false);}}
return <Screen><Header eyebrow="Yönetim" title={employee?'Personeli düzenle':'Yeni personel'} subtitle="Yetki, hesap ve operasyon sınırlarını tek yerde yönetin."/><SectionTitle title="Personel bilgileri"/><Card><Field label="Personel kodu" value={code} onChangeText={setCode} autoCapitalize="characters" placeholder="PRS-001"/><Field label="Ad soyad" value={name} onChangeText={setName} placeholder="Ad Soyad"/><Field label="Telefon" value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><Field label="İndirim limiti (%)" value={discount} onChangeText={setDiscount} keyboardType="decimal-pad"/><Toggle label="Tahsilat yetkisi" detail="Personel müşteri tahsilatı bildirebilir." value={collect} onChange={setCollect}/><Toggle label="Aktif personel" value={active} onChange={setActive}/></Card><SectionTitle title="Kullanıcı hesabı" detail="Mobil ve web erişimi"/><Card>{!employee?.user_id?<Toggle label="Giriş hesabı oluştur" value={createAccount} onChange={setCreateAccount}/>:<Text style={{color:colors.muted}}>Bağlı kullanıcı hesabının rolünü veya parolasını güncelleyebilirsiniz.</Text>}{createAccount||employee?.user_id?<><Text style={{fontWeight:'800',color:colors.navy}}>Görev</Text><ChoiceChips items={roles} value={role} label={x=>x.name} onSelect={setRole}/>{!employee?.user_id?<Field label="Giriş e-postası" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none"/>:null}<Field label={employee?.user_id?'Yeni parola (isteğe bağlı)':'Başlangıç parolası'} value={password} onChangeText={setPassword} secureTextEntry hint="En az 6 karakter"/></>:null}</Card><Button title={employee?'Değişiklikleri kaydet':'Personeli oluştur'} icon="checkmark-circle" onPress={save} loading={saving}/></Screen>}
