import { Controller, useForm } from 'react-hook-form';
import * as Crypto from 'expo-crypto';
import { router, useLocalSearchParams } from 'expo-router';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { api, ApiError } from '@/api';
import { Button, Field, Header, Screen } from '@/components';
import { queue } from '@/outbox';
import { colors } from '@/theme';
type Form={activity_type:'call'|'note'|'follow_up';subject:string;notes:string;next_action_at:string};
const crypto=Crypto;
const types=[['call','Telefon'],['note','Not'],['follow_up','Takip']] as const;
export default function Activity(){const{id}=useLocalSearchParams<{id:string}>();const{control,watch,setValue,handleSubmit,setError,formState:{isSubmitting,errors}}=useForm<Form>({defaultValues:{activity_type:'call',subject:'',notes:'',next_action_at:''}});const selected=watch('activity_type');const submit=handleSubmit(async value=>{if(!value.subject.trim()){setError('subject',{message:'Konu zorunlu.'});return;}try{await api(`/customers/${id}/activities`,{method:'POST',body:JSON.stringify(value),idempotencyKey:crypto.randomUUID()});router.back();}catch(error){if(error instanceof ApiError&&error.status>0){setError('root',{message:error.message});return;}await queue('customer.activity','POST',`/customers/${id}/activities`,value);Alert.alert('Gorusme kaydedildi','Baglanti geldiginde senkronizasyon ekranindan gonderebilirsiniz.');router.back();}});return <Screen><Header title="Gorusme ekle"/><View style={styles.types}>{types.map(([value,label])=><Pressable key={value} onPress={()=>setValue('activity_type',value)} style={[styles.type,selected===value&&styles.selected]}><Text style={[styles.typeText,selected===value&&styles.selectedText]}>{label}</Text></Pressable>)}</View><Controller control={control} name="subject" render={({field})=><Field label="Konu" value={field.value} onChangeText={field.onChange} error={errors.subject?.message}/>}/><Controller control={control} name="notes" render={({field})=><Field label="Notlar" value={field.value} onChangeText={field.onChange} multiline/>}/><Controller control={control} name="next_action_at" render={({field})=><Field label="Sonraki islem tarihi" placeholder="2026-07-25 10:00" value={field.value} onChangeText={field.onChange}/>}/>{errors.root?.message?<Text style={styles.error}>{errors.root.message}</Text>:null}<Button title="Gorusmeyi kaydet" onPress={submit} loading={isSubmitting}/></Screen>}
const styles=StyleSheet.create({types:{flexDirection:'row',gap:8},type:{minHeight:48,flex:1,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.border,borderRadius:8,backgroundColor:'#fff'},selected:{backgroundColor:colors.navy,borderColor:colors.navy},typeText:{color:colors.text,fontWeight:'700'},selectedText:{color:'#fff'},error:{color:colors.danger}});
