import { useQuery, useQueryClient } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Alert } from 'react-native';
import { api, ApiError } from '../../../src/api';
import { Button, Card, ErrorState, Field, Header, Loading, Screen, Toggle } from '../../../src/components';
type Contact={full_name:string;phone:string;email?:string};type Customer={id:number;company_name:string;city:string;district:string;address?:string;delivery_address?:string;tax_number?:string;status:string;updated_at:string;contacts:Contact[]};
export default function EditCustomer(){
  const{id}=useLocalSearchParams<{id:string}>();const client=useQueryClient();const q=useQuery({queryKey:['customer',id],queryFn:()=>api<{data:Customer}>(`/customers/${id}`)});
  const[company,setCompany]=useState<string>();const[city,setCity]=useState<string>();const[district,setDistrict]=useState<string>();const[address,setAddress]=useState<string>();const[delivery,setDelivery]=useState<string>();const[tax,setTax]=useState<string>();const[contact,setContact]=useState<string>();const[phone,setPhone]=useState<string>();const[email,setEmail]=useState<string>();const[active,setActive]=useState(true);const[saving,setSaving]=useState(false);
  if(q.isLoading)return<Loading/>;if(q.isError||!q.data)return<Screen><ErrorState retry={()=>void q.refetch()}/></Screen>;
  const d=q.data.data;const primary=d.contacts[0];
  async function save(){setSaving(true);try{await api(`/customers/${id}`,{method:'PUT',body:JSON.stringify({company_name:company??d.company_name,city:city??d.city,district:district??d.district,address:address??d.address,delivery_address:delivery??d.delivery_address,tax_number:tax??d.tax_number,contact_name:contact??primary?.full_name,contact_phone:phone??primary?.phone,contact_email:email??primary?.email,status:active?'active':'passive',expected_updated_at:d.updated_at})});await client.invalidateQueries({queryKey:['customer',id]});router.back();}catch(e){Alert.alert('Müşteri kaydedilemedi',e instanceof ApiError?e.message:'Bağlantı kurulamadı.');}finally{setSaving(false);}}
  return <Screen><Header eyebrow="Müşteri yönetimi" title="Müşteriyi düzenle" subtitle={d.company_name}/><Card><Field label="Firma adı" value={company??d.company_name} onChangeText={setCompany}/><Field label="İl" value={city??d.city} onChangeText={setCity}/><Field label="İlçe" value={district??d.district} onChangeText={setDistrict}/><Field label="Adres" value={address??d.address??''} onChangeText={setAddress} multiline/><Field label="Teslimat adresi" value={delivery??d.delivery_address??''} onChangeText={setDelivery} multiline/><Field label="Vergi numarası" value={tax??d.tax_number??''} onChangeText={setTax}/><Toggle label="Aktif müşteri" value={active} onChange={setActive}/></Card><Card><Field label="Yetkili kişi" value={contact??primary?.full_name??''} onChangeText={setContact}/><Field label="Telefon" value={phone??primary?.phone??''} onChangeText={setPhone} keyboardType="phone-pad"/><Field label="E-posta" value={email??primary?.email??''} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none"/></Card><Button title="Değişiklikleri kaydet" icon="checkmark-circle" onPress={save} loading={saving}/></Screen>;
}
