<?php
declare(strict_types=1);
namespace App\Database\Migrations;
use CodeIgniter\Database\Migration;
class CreateCommissionTables extends Migration
{
    public function up():void
    {
        $this->forge->addField(['id'=>['type'=>'BIGINT','constraint'=>20,'unsigned'=>true,'auto_increment'=>true],'name'=>['type'=>'VARCHAR','constraint'=>120],'base_type'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'sales'],'rate_percent'=>['type'=>'DECIMAL','constraint'=>'5,2'],'employee_id'=>['type'=>'INT','constraint'=>11,'unsigned'=>true,'null'=>true],'product_category_id'=>['type'=>'INT','constraint'=>11,'unsigned'=>true,'null'=>true],'starts_on'=>['type'=>'DATE'],'ends_on'=>['type'=>'DATE','null'=>true],'is_active'=>['type'=>'BOOLEAN','default'=>true],'created_by_user_id'=>['type'=>'INT','constraint'=>11,'unsigned'=>true],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]]);$this->forge->addKey('id',true);$this->forge->addKey(['starts_on','ends_on','is_active']);$this->forge->addForeignKey('employee_id','employees','id','CASCADE','SET NULL');$this->forge->addForeignKey('product_category_id','product_categories','id','CASCADE','SET NULL');$this->forge->addForeignKey('created_by_user_id','users','id','CASCADE','RESTRICT');$this->forge->createTable('commission_rules',true);
        $this->forge->addField(['id'=>['type'=>'BIGINT','constraint'=>20,'unsigned'=>true,'auto_increment'=>true],'period_code'=>['type'=>'VARCHAR','constraint'=>30],'starts_on'=>['type'=>'DATE'],'ends_on'=>['type'=>'DATE'],'status'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'open'],'closed_by_user_id'=>['type'=>'INT','constraint'=>11,'unsigned'=>true,'null'=>true],'closed_at'=>['type'=>'DATETIME','null'=>true],'paid_at'=>['type'=>'DATETIME','null'=>true],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]]);$this->forge->addKey('id',true);$this->forge->addUniqueKey('period_code');$this->forge->addForeignKey('closed_by_user_id','users','id','CASCADE','SET NULL');$this->forge->createTable('commission_periods',true);
        $this->forge->addField(['id'=>['type'=>'BIGINT','constraint'=>20,'unsigned'=>true,'auto_increment'=>true],'commission_rule_id'=>['type'=>'BIGINT','constraint'=>20,'unsigned'=>true],'sales_document_id'=>['type'=>'BIGINT','constraint'=>20,'unsigned'=>true],'sales_employee_id'=>['type'=>'INT','constraint'=>11,'unsigned'=>true],'commission_period_id'=>['type'=>'BIGINT','constraint'=>20,'unsigned'=>true,'null'=>true],'base_amount'=>['type'=>'DECIMAL','constraint'=>'15,2'],'rate_percent'=>['type'=>'DECIMAL','constraint'=>'5,2'],'commission_amount'=>['type'=>'DECIMAL','constraint'=>'15,2'],'status'=>['type'=>'VARCHAR','constraint'=>20,'default'=>'pending'],'calculation_snapshot'=>['type'=>'TEXT'],'created_at'=>['type'=>'DATETIME','null'=>true],'updated_at'=>['type'=>'DATETIME','null'=>true]]);$this->forge->addKey('id',true);$this->forge->addUniqueKey(['commission_rule_id','sales_document_id','sales_employee_id']);$this->forge->addKey(['sales_employee_id','status']);$this->forge->addForeignKey('commission_rule_id','commission_rules','id','CASCADE','RESTRICT');$this->forge->addForeignKey('sales_document_id','sales_documents','id','CASCADE','RESTRICT');$this->forge->addForeignKey('sales_employee_id','employees','id','CASCADE','RESTRICT');$this->forge->addForeignKey('commission_period_id','commission_periods','id','CASCADE','SET NULL');$this->forge->createTable('commission_entries',true);
    }
    public function down():void{$this->forge->dropTable('commission_entries',true);$this->forge->dropTable('commission_periods',true);$this->forge->dropTable('commission_rules',true);}
}
