<?= $this->extend('layouts/panel') ?>
<?= $this->section('content') ?>
<?php $errors = session('errors') ?? []; $value = static fn(string $key, mixed $fallback = '') => old($key, $fallback); ?>
<div class="form-heading"><a class="back-link" href="<?= site_url('panel/siparisler') ?>">← Teklif ve siparişler</a><p class="page-lead">Fiyatlar ve bütün toplamlar kayıtta sunucu tarafında yeniden hesaplanır.</p></div>
<?php if ($errors): ?><div class="alert alert--error"><strong>Belge kaydedilemedi.</strong><span><?= esc(reset($errors)) ?></span></div><?php endif; ?>
<form class="sales-document-form" method="post" action="<?= $document ? site_url('panel/siparisler/'.$document['id'].'/duzenle') : site_url('panel/siparisler/yeni') ?>" data-sales-document data-price-url="<?= site_url('panel/siparisler/fiyat') ?>">
<?= csrf_field() ?><input type="hidden" name="document_type" value="<?= esc($documentType) ?>"><input type="hidden" name="client_reference" value="<?= esc($clientReference) ?>" data-client-reference><input type="hidden" name="items_json" data-items-json><input type="hidden" name="intent" value="draft" data-intent>
<textarea hidden data-catalog-json><?= esc(json_encode($catalog, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)) ?></textarea><textarea hidden data-initial-items><?= esc(json_encode($items, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)) ?></textarea>
<section class="form-card"><div class="form-card__head"><span class="step-number">1</span><div><h2>Belge bilgileri</h2><p><?= esc($documentType === 'quote' ? 'Teklif' : 'Sipariş') ?> için müşteri ve satış sorumlusu.</p></div></div><div class="form-grid"><label class="field"><span>Müşteri <b>*</b></span><select name="customer_id" required data-sales-customer><option value="">Müşteri seçin</option><?php foreach ($customers as $customer): ?><option value="<?= esc($customer['id']) ?>" <?= (int) $value('customer_id', $customerId) === (int) $customer['id'] ? 'selected' : '' ?>><?= esc($customer['company_name'].' · '.$customer['customer_code']) ?></option><?php endforeach; ?></select></label><?php if ($canChooseEmployee): ?><label class="field"><span>Satışın ait olduğu personel</span><select name="sales_employee_id"><option value="">Müşteri sorumlusu</option><?php foreach ($employees as $person): ?><option value="<?= esc($person['id']) ?>" <?= (int) $value('sales_employee_id', $document['sales_employee_id'] ?? 0) === (int) $person['id'] ? 'selected' : '' ?>><?= esc($person['full_name']) ?></option><?php endforeach; ?></select></label><?php endif; ?><label class="field field--wide"><span>Teslimat adresi <?= $documentType === 'order' ? '<b>*</b>' : '' ?></span><textarea name="delivery_address" rows="3" placeholder="<?= esc($documentType === 'order' ? 'Sipariş oluşturulurken zorunludur' : 'Teslimat adresi') ?>"><?= esc($value('delivery_address', $document['delivery_address'] ?? '')) ?></textarea></label><label class="field"><span>Talep edilen teslim tarihi</span><input type="date" name="requested_delivery_date" value="<?= esc($value('requested_delivery_date', $document['requested_delivery_date'] ?? '')) ?>"></label><label class="field"><span>Belge notu</span><textarea name="notes" rows="3"><?= esc($value('notes', $document['notes'] ?? '')) ?></textarea></label></div></section>
<?php if ($documentType === 'order'): ?>
<section class="form-card">
    <div class="form-card__head"><span class="step-number">2</span><div><h2>Operasyon sorumluları</h2><p>Sipariş hazırlanırken görev alacak personelleri seçin.</p></div></div>
    <div class="form-grid">
        <label class="field"><span>Siparişi hazırlayacak kişi <b>*</b></span><select name="preparation_employee_id"><option value="">Personel seçin</option><?php foreach ($employees as $person): ?><option value="<?= esc($person['id']) ?>" <?= (int) $value('preparation_employee_id', $document['preparation_employee_id'] ?? 0) === (int) $person['id'] ? 'selected' : '' ?>><?= esc($person['full_name']) ?></option><?php endforeach; ?></select></label>
        <label class="field"><span>Tasarımı yapacak kişi <b>*</b></span><select name="design_employee_id"><option value="">Personel seçin</option><?php foreach ($employees as $person): ?><option value="<?= esc($person['id']) ?>" <?= (int) $value('design_employee_id', $document['design_employee_id'] ?? 0) === (int) $person['id'] ? 'selected' : '' ?>><?= esc($person['full_name']) ?></option><?php endforeach; ?></select></label>
        <label class="field"><span>Baskıyı yapacak kişi <b>*</b></span><select name="print_employee_id"><option value="">Personel seçin</option><?php foreach ($employees as $person): ?><option value="<?= esc($person['id']) ?>" <?= (int) $value('print_employee_id', $document['print_employee_id'] ?? 0) === (int) $person['id'] ? 'selected' : '' ?>><?= esc($person['full_name']) ?></option><?php endforeach; ?></select></label>
        <p class="field field--wide muted">Taslak kaydederken boş bırakılabilir; siparişi oluştururken üç seçim de zorunludur.</p>
    </div>
</section>
<?php endif; ?>
<section class="form-card sales-lines-card"><div class="form-card__head"><span class="step-number"><?= $documentType === 'order' ? '3' : '2' ?></span><div><h2>Ürünler</h2><p>Satışa açık ve geçerli fiyatı bulunan varyantlar.</p></div></div><?php if (! $catalog): ?><div class="alert alert--error"><strong>Seçilebilir ürün bulunamadı.</strong><span>Ürün yönetiminde ürünü satışa açın ve sıfırdan büyük liste ya da özel fiyat tanımlayın.</span></div><?php endif; ?><div class="product-picker"><input type="search" data-product-search placeholder="Ürün, kod, beden veya renk ara" <?= ! $catalog ? 'disabled' : '' ?>><select data-product-picker <?= ! $catalog ? 'disabled' : '' ?>><option value="">Ürün varyantı seçin</option><?php foreach ($catalog as $entry): ?><option value="<?= $entry['product_id'].':'.$entry['variant_id'] ?>"><?= esc($entry['name'].' · '.($entry['variant'] ?: 'Standart').' · '.$entry['sku']) ?></option><?php endforeach; ?></select><button class="button" type="button" data-add-line <?= ! $catalog ? 'disabled' : '' ?>>Ürün ekle</button></div><div class="sales-lines" data-sales-lines><p class="muted" data-empty-lines>Henüz ürün eklenmedi.</p></div></section>
<section class="form-card sales-summary"><div><span>Ara toplam</span><strong data-summary-subtotal>0,00 ₺</strong></div><div><span>İndirim</span><strong data-summary-discount>0,00 ₺</strong></div><div><span>Vergi</span><strong data-summary-tax>0,00 ₺</strong></div><div class="sales-summary__grand"><span>Genel toplam</span><strong data-summary-grand>0,00 ₺</strong></div></section>
<div class="offline-state" data-draft-state role="status">Taslak hazırlanıyor</div><div class="form-actions sales-form-actions"><a class="button button--secondary" href="<?= site_url('panel/siparisler') ?>">Vazgeç</a><span></span><button class="button button--secondary" type="submit" data-save-intent="draft">Taslak kaydet</button><?php if ($documentType === 'order'): ?><button class="button" type="submit" data-save-intent="submit">Siparişi oluştur</button><?php else: ?><button class="button" type="submit" data-save-intent="submit">Onaya gönder</button><?php endif; ?></div>
</form>
<?= $this->endSection() ?>
<?= $this->section('scripts') ?><script src="<?= base_url('assets/js/sales-documents.js') ?>" defer></script><?= $this->endSection() ?>
