import { useQuery } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { Linking, StyleSheet, Text, View } from 'react-native';
import { api } from '@/api';
import { Button, Card, Header, Loading, Screen } from '@/components';
import { colors } from '@/theme';
type Detail={data:{id:number;company_name:string;customer_code:string;city:string;district:string;address?:string;delivery_address?:string;contacts:Array<{id:number;full_name:string;phone:string;email?:string}>;activities:Array<{id:number;subject:string;notes?:string;happened_at:string}>}};
export default function CustomerDetail(){const{id}=useLocalSearchParams<{id:string}>();const query=useQuery({queryKey:['customer',id],queryFn:()=>api<Detail>(`/customers/${id}`)});if(query.isLoading)return<Loading/>;const c=query.data?.data;if(!c)return<Screen><Text>Musteri bulunamadi.</Text></Screen>;const contact=c.contacts[0];return <Screen><Header title={c.company_name} subtitle={`${c.customer_code} - ${c.city}/${c.district}`} action={<Button title="+ Gorusme" onPress={()=>router.push(`/customer/${id}/activity`)}/>}/>{contact?<Card><Text style={styles.title}>{contact.full_name}</Text><View style={styles.actions}><Button title="Ara" onPress={()=>Linking.openURL(`tel:${contact.phone}`)}/><Button title="WhatsApp" secondary onPress={()=>Linking.openURL(`https://wa.me/${contact.phone.replace(/\D/g,'')}`)}/></View><Text>{contact.phone}</Text>{contact.email?<Text>{contact.email}</Text>:null}</Card>:null}<Card><Text style={styles.title}>Adres</Text><Text style={styles.text}>{c.delivery_address||c.address||'Adres girilmemis.'}</Text></Card><Text style={styles.section}>Gorusme gecmisi</Text>{c.activities.length?c.activities.map(a=><Card key={a.id}><Text style={styles.title}>{a.subject}</Text><Text style={styles.date}>{new Date(a.happened_at).toLocaleString('tr-TR')}</Text>{a.notes?<Text style={styles.text}>{a.notes}</Text>:null}</Card>):<Text style={styles.date}>Henuz gorusme yok.</Text>}</Screen>}
const styles=StyleSheet.create({title:{fontSize:17,fontWeight:'700',color:colors.navy},actions:{flexDirection:'row',gap:8},text:{color:colors.text,lineHeight:21},date:{color:colors.muted},section:{fontSize:20,fontWeight:'800',color:colors.navy}});
